[build]
  command = "npm install -g @angular/cli && npm install && ng build"
  publish = "dist/angular-app"


[build.environment]
  NODE_VERSION = "16"


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200